name: Backend Static Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip and install packages
        run: |
          pip3 install --upgrade pip
          pip3 install -r ./backend/requirements.dev.txt

      - name: Format with Black
        run: black --config=./backend/pyproject.toml --preview ./backend

      - name: Lint with Flake8
        run: flake8 --config=./backend/.flake8 ./backend
